- name: catalogue service
  hosts: catalogue
  become: yes
  tasks: 
  - name: disable the old nodejs and enable to the nodejs
    ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:20 -y
    #Shell and command module, shell with login to target server to run 

  - name: install the nodejs
    ansible.builtin.dnf:
     name: nodejs
     state: present

  - name: create user
    ansible.builtin.user: #Ansible user module
     name: roboshop
     shell: /sbin/nologin
     system: true
     home: /app

  - name: create directory
    ansible.builtin.file: #Ansible file module
     path: /app
     state: directory

  - name: download the code
    ansible.builtin.get_url:  #Ansible get url module
     url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
     dest: /tmp/catalogue.zip

  - name: extract the zip file
    ansible.builtin.unarchive: #Ansible unzip module
     src: /tmp/catalogue.zip
     dest: /app
     remote_src: yes #Because the file is already available in remote server 

  - name: install dependencies
    community.general.npm:
     name: npm
     path: /app

  - name: copy the catalogue service to system 
    ansible.builtin.copy:
     src: catalogue.service
     dest: /etc/systemd/system/catalogue.service

  - name: system daemon reload
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: Start and enable catalogue service
    ansible.builtin.service:
     name: catalogue
     state: started
     enabled: yes

  - name: copy the mongodb repo file
    ansible.builtin.copy: #Search ansible copy module in google to find the modules
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
     name: mongodb-mongosh
     state: present

  - name: get the catalogue count  #if the count is 0 i.e, no data in catalogue server
    ansible.builtin.command: mongosh --host mongodb.neeraj.sbs --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  - name: print the count
    ansible.builtin.debug:
     msg: "catalogue count is : {{ catalogue_count }} "
     
    