- name: configure payment server
  hosts: payment
  become: yes
  tasks:
  - name: install python3 packages
    ansible.builtin.dnf:
     name: "{{ item }}"
     state: present
    loop:
    - python3 
    - gcc 
    - python3-devel
  
  - name: create app directory
    ansible.builtin.file:
     path: /app
     state: directory


  - name: create user
    ansible.builtin.user:
     name: roboshop
     shell: /sbin/nologin
     system: true
     home: /app

  - name: download the  payment code
    ansible.builtin.get_url:  #Ansible get url module
     url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
     dest: /tmp/payment.zip

  - name: extract the zip file
    ansible.builtin.unarchive: #Ansible unzip module
     src: /tmp/payment.zip
     dest: /app
     remote_src: yes #Because the file is already available in remote server

  - name: isntall dependencies
    ansible.builtin.pip:
     requirements:  requirements.txt
     executable: pip3.9
    args:
     chdir: /app
  
  - name: copy payment service
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: daemon reload
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: enable and start payment
    ansible.builtin.service:
      name: payment
      state: started
      enabled: yes


