- name: install redis component
  hosts: redis
  become: yes
  tasks:
  - name: disable redis
    ansible.builtin.command: dnf module disable nodejs -y; dnf module enable redis:7 -y
  
  - name: install redis
    ansible.builtin.dnf:
     name: redis
     state: present

  - name: allo remote connection
    ansible.builtin.replace:
     path:  /etc/redis/redis.conf
     regexp: '127.0.0.1'
     replace: '0.0.0.0'
    
  - name: replace protection mode 
    ansible.builtin.lineinfile:
     path: /etc/redis/redis.conf
     regexp: 'protected-mode'
     replace: protected-mode no

    